const mockProducts = [
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p1/1.png",
    name: "Angrakha kurti",
    brand: "Angrakha",
    price: 1500,
    realPrice: 5000,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p1/1.png",
      process.env.PUBLIC_URL + "../Images/p1/2.png",
      process.env.PUBLIC_URL + "../Images/p1/3.png",
      process.env.PUBLIC_URL + "../Images/p1/4.png",
      process.env.PUBLIC_URL + "../Images/p1/5.png",
    ],
  },

  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Men Cotton T-shirt",
    price: 999.0,
    realPrice: 1500.0,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p3/1.webp",
    name: "Printed Cotton T-shirt",
    price: 999.0,
    realPrice: 1500.0,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p3/1.webp",
      process.env.PUBLIC_URL + "../Images/p3/2.webp",
      process.env.PUBLIC_URL + "../Images/p3/3.webp",
      process.env.PUBLIC_URL + "../Images/p3/4.webp",
      process.env.PUBLIC_URL + "../Images/p3/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p4/1.webp",
    name: "Slim Cotton T-shirt",
    price: 1400,
    realPrice: 2400,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p4/1.webp",
      process.env.PUBLIC_URL + "../Images/p4/2.webp",
      process.env.PUBLIC_URL + "../Images/p4/3.webp",
      process.env.PUBLIC_URL + "../Images/p4/4.webp",
      process.env.PUBLIC_URL + "../Images/p4/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p5/1.webp",
    name: "Slim Rapid T-shirt",
    price: 1250,
    realPrice: 2800,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p5/1.webp",
      process.env.PUBLIC_URL + "../Images/p5/2.webp",
      process.env.PUBLIC_URL + "../Images/p5/3.webp",
      process.env.PUBLIC_URL + "../Images/p5/4.webp",
      process.env.PUBLIC_URL + "../Images/p5/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p6/1.webp",
    name: "Rapid Cotton T-shirt",
    price: 1800,
    realPrice: 3400,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p6/1.webp",
      process.env.PUBLIC_URL + "../Images/p6/2.webp",
      process.env.PUBLIC_URL + "../Images/p6/3.webp",
      process.env.PUBLIC_URL + "../Images/p6/4.webp",
      process.env.PUBLIC_URL + "../Images/p6/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p7/1.webp",
    name: "Sleeved T-shirt",
    price: 1765,
    realPrice: 3175,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p7/1.webp",
      process.env.PUBLIC_URL + "../Images/p7/2.webp",
      process.env.PUBLIC_URL + "../Images/p7/3.webp",
      process.env.PUBLIC_URL + "../Images/p7/4.webp",
      process.env.PUBLIC_URL + "../Images/p7/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p8/1.webp",
    name: "Graphic Cotton T-shirt",
    price: 2200,
    realPrice: 4200,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p8/1.webp",
      process.env.PUBLIC_URL + "../Images/p8/2.webp",
      process.env.PUBLIC_URL + "../Images/p8/3.webp",
      process.env.PUBLIC_URL + "../Images/p8/4.webp",
      process.env.PUBLIC_URL + "../Images/p8/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p9/1.webp",
    name: "Colourblocked Cotton T-shirt",
    price: 2100,
    realPrice: 4000,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p9/1.webp",
      process.env.PUBLIC_URL + "../Images/p9/2.webp",
      process.env.PUBLIC_URL + "../Images/p9/3.webp",
      process.env.PUBLIC_URL + "../Images/p9/4.webp",
      process.env.PUBLIC_URL + "../Images/p9/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p10/1.webp",
    name: "Pure Cotton T-shirt",
    price: 785,
    realPrice: 1200,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p10/1.webp",
      process.env.PUBLIC_URL + "../Images/p10/2.webp",
      process.env.PUBLIC_URL + "../Images/p10/3.webp",
      process.env.PUBLIC_URL + "../Images/p10/4.webp",
      process.env.PUBLIC_URL + "../Images/p10/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p11/1.webp",
    name: "Men Cotton T-shirt",
    price: 1200,
    realPrice: 2900,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p11/1.webp",
      process.env.PUBLIC_URL + "../Images/p11/2.webp",
      process.env.PUBLIC_URL + "../Images/p11/3.webp",
      process.env.PUBLIC_URL + "../Images/p11/4.webp",
      process.env.PUBLIC_URL + "../Images/p11/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p12/1.webp",
    name: "Printed kurti",
    price: 550,
    realPrice: 1900,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p12/1.webp",
      process.env.PUBLIC_URL + "../Images/p12/2.webp",
      process.env.PUBLIC_URL + "../Images/p12/3.webp",
      process.env.PUBLIC_URL + "../Images/p12/4.webp",
      process.env.PUBLIC_URL + "../Images/p12/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 1550,
    realPrice: 2500,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 2150,
    realPrice: 3500,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 950,
    realPrice: 1500,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 1950,
    realPrice: 3100,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 1550,
    realPrice: 3100,

    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 2550,
    realPrice: 4200,

    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 1999,
    realPrice: 3200,

    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 999,
    realPrice: 2200,

    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 899,
    realPrice: 2200,

    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 1899,
    realPrice: 3200,

    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Men Cotton T-shirt",
    price: 1399,
    realPrice: 3100,

    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 2199,
    realPrice: 3100,
    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
  {
    imageURL: process.env.PUBLIC_URL + "../Images/p2/1.webp",
    name: "Printed kurti",
    price: 2899,
    realPrice: 4100,

    brand: "Roadster",
    images: [
      process.env.PUBLIC_URL + "../Images/p2/1.webp",
      process.env.PUBLIC_URL + "../Images/p2/2.webp",
      process.env.PUBLIC_URL + "../Images/p2/3.webp",
      process.env.PUBLIC_URL + "../Images/p2/4.webp",
      process.env.PUBLIC_URL + "../Images/p2/5.webp",
    ],
  },
];

export default mockProducts;
